### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by DominusKelvin** [sailscastshq/boring-stack#10]
README should be updated showing the ecosystem of packages that makes up The Boring JavaScript Stack as well as contributors to the boring-stack repo

**Comment by lennyAiko** [comment]
I am about to add the beautiful way to set up ;-), To enable users to just copy and paste the command

For Vue
`npx create-sails <project-name> --vue`

For React
`npx create-sails <project-name> --react`

For Svelte
`npx create-sails <project-name> --svelte`
