### ISSUE TITLE
Resolve error: Can't resolve 'vue'

### ISSUE THREAD

**Issue by Parallax18** [sailscastshq/boring-stack#111]
### Description
Trying out TBJS. Created a new project - npx create-sails trying-sails-vue --vue - but it fails when I run the project.

This is the error -  Resolve error: Can't resolve 'vue'

...

### Current behavior

Apparently, vue is not added to the dependencies. Some of my findings show that this may not be particular to TBJS. But I think it needs to be looked into.

<img width="400" alt="Screenshot 2024-08-25 at 03 19 36" src="https://github.com/user-attachments/assets/dfb69f9e-be7a-4e5c-a983-2aa4a1cdd7d0">

...

### Expected behavior
Vuejs should be listed as a dependency and installed when `yarn install` is run.

...

> Replace space in square bracket with `x` e.g `[x]`

[ ] I have checked and this issue does not exist

**Comment by DominusKelvin** [comment]
On second look, you are right @Parallax18 and the new version of mellow-vue I'm releasing this week will fix that

**Comment by Parallax18** [comment]
@DominusKelvin Awesome.

**Comment by DominusKelvin** [comment]
This has been resolved so closing now @Parallax18
