### ISSUE TITLE
Add Mellow template

### ISSUE THREAD

**Issue by DominusKelvin** [sailscastshq/boring-stack#13]
Mellow is the default starter template of the Boring Stack. The Boring Stack Mellow is a minimal, simple implementation of User authentication, including 

- login, 
- registration, 
- password reset, 
- email verification, and 
- password confirmation. 

In addition, Mellow includes a simple "profile" page where your user can update their name, email address, and password.

**Comment by babblebey** [comment]
Hi @DominusKelvin 

Is there some sort of design (figma) file to guide the development of this views?

**Comment by DominusKelvin** [comment]
Hey @babblebey there is none, I do have an idea of how the will look mostly just minimal but still useful that folks will build on top of them.

I put out a Tweet for designers who want to contribute to creating the design for Mello. If I don't have any feedback, I will do the designs myself as we plan to get Mellow ready at least for Vue by Wednesday

**Comment by babblebey** [comment]
Sounds great @DominusKelvin 

That can then be replicated for React and Svelte for sure.

**Comment by DominusKelvin** [comment]
> Sounds great @DominusKelvin 
> 
> That can then be replicated for React and Svelte for sure. 

Yeah exactly. Mellow is first of several templates we will be building to help folks either use them as the basis for their next fullstack JavaScript project or as guides


@babblebey which of these frontend frameworks do you write? Or are you solely backend?

**Comment by babblebey** [comment]
That's a fine one there @DominusKelvin.

I will be contributing to the React ⚛️ templates, and be willing to dabble on the backend a little bit too, when I can.

**Comment by DominusKelvin** [comment]
Here is the link for the design of mellow on Figma

https://www.figma.com/file/VQFwlNIP2ZCfQadSqKE8D0/Mellow?type=design&node-id=0-1&mode=design&t=ElSotHFgb9eKcOev-0

**Comment by babblebey** [comment]
> Here is the link for the design of mellow on Figma
> 
> https://www.figma.com/file/VQFwlNIP2ZCfQadSqKE8D0/Mellow?type=design&node-id=0-1&mode=design&t=ElSotHFgb9eKcOev-0

Great Stuff @DominusKelvin

Let's get to it.
