### ISSUE TITLE
Add Mellow template for React

### ISSUE THREAD

**Issue by DominusKelvin** [sailscastshq/boring-stack#17]
Related to issue #13

**Comment by Semako123** [comment]
Hi there! I'm interested in working on this issue. I've checked the Figma file and I just wanted to confirm the location where I should build the landing page.

Based on my understanding, I should build the landing page into the `mellow-react/assets/js` folder, is that correct? Please let me know if there are any additional details or specific instructions regarding the file structure or any other requirements for implementing the landing page.

I'm looking forward to working on this issue and actively contributing to the project. Thank you!

**Comment by DominusKelvin** [comment]
Hey @Semako123 thanks for your interest on working on this but currently I need to set the foundation for the mellow templates with the Vue one so work on the templates will be blocked until the template for Vue ships with will contain a working implementation of what every other template needs with the only change is the UI(which will be built on React)

I'll update this issue and also discussions when we are ready to move forward 

Thank you for your interest and you can also join the Discord to stay in the loop

https://sailscasts.com/chat

**Comment by Semako123** [comment]
Okay, thank you very much.
