### ISSUE TITLE
Web bundler 

### ISSUE THREAD

**Issue by David-glitc** [sailscastshq/boring-stack#19]
I think there should be an option for vite since it’s something most people would like to opt for @

**Comment by DominusKelvin** [comment]
That's interesting, so currently we are using Webpack 5 for asset bundling. When Sails Shipwright gets shipped, we will switch to using that as well.

Sails Shipwright is the modern asset pipeline for Sails based on ESBuild which is also the bundler powering Vite.

**Comment by David-glitc** [comment]
Great love this...

saw the project on Twitter just dropped by hope to start contributing soon
