### ISSUE TITLE
typo: mention of "Vue 3" in README for mellow-react and mellow-svelte

### ISSUE THREAD

**Issue by babblebey** [sailscastshq/boring-stack#26]
You can find mention of "Vue 3" on the READMEs of the `mellow-react` and `mellow-svelte`. 

[templates\mellow-react\README.md](https://github.com/babblebey/boring-stack/tree/develop/templates/mellow-react#readme)
```md
This template should help get you started developing with a modern Sails fullstack application with Inertia and Vue 3
```

[templates\mellow-svelte\README.md](https://github.com/babblebey/boring-stack/tree/develop/templates/mellow-svelte#readme)
```md
This template should help get you started developing with a modern Sails fullstack application with Inertia and Vue 3
```

It should read the respective libraries for sure.

**Comment by babblebey** [comment]
Changing the "Vue 3" to respective libraries in their templates.

This can seat as a `good-first-issue`

**Comment by DominusKelvin** [comment]
Thanks for catching this. The copy of these README will be significantly changed and as a side effect, the issue you raised will be addressed @babblebey 

But for now since we are still scaffolding the counter apps, you can go ahead and open a PR to fix this

**Comment by Emmo00** [comment]
Hello @babblebey and @DominusKelvin , I understand this is a little temporary fix as more content is gonna be added soon, but don't you think we should do it anyways?

**Comment by DominusKelvin** [comment]
Yeah any one is welcomed to open a PR to fix this. You can also touch the package.json if respective templates to update their name as well. Thanks

**Comment by Emmo00** [comment]
I'm sorry, i don't see what needs to be changed in the package.json file. i was thinking it was the description but that is probably right.
![image](https://github.com/sailscastshq/boring-stack/assets/88244468/ac567179-8384-482a-b655-76578af8094b)

**Comment by DominusKelvin** [comment]
@Emmo00 the name that's currently set to svelte should be "mellow-svelte" or "mellow-react" and "mellow-vue" respectively

**Comment by Emmo00** [comment]
oh.. thanks
