### ISSUE TITLE
Add jsconfig.json to the boring-stack

### ISSUE THREAD

**Issue by DominusKelvin** [sailscastshq/boring-stack#32]
Primarily this will be used to have to enforce TypeScript checking in JavaScript files in VS Code.

**Comment by Emmo00** [comment]
I think this should be added to every template folder? Can I work on this?

**Comment by DominusKelvin** [comment]
Nice you want to work on this @Emmo00, I'm currently cutting out a release that will have those changes already :)

**Comment by Emmo00** [comment]
Oh ... Ok, I actually have a commit ready, just remaining to push, No problem @DominusKelvin 👍
