### ISSUE TITLE
Add the "How to Contribute to Open Source by Kelvin" link to the contributing. md file

### ISSUE THREAD

**Issue by geekiedj** [sailscastshq/boring-stack#33]
Having this link [How to Contribute to Open source by Kelvin](https://www.youtube.com/watch?v=Vqjzl9f3lGM) in the contributing.md makes it easier for first-timers to watch and become familiar with open source in general.

**Comment by DominusKelvin** [comment]
Awesome stuff @geekiedj. Let's make sure to call out that this is for first time contributors to open source. I believe it will set the tone for the sort of contributors we expect on this project.

Thank you for taking this on @geekiedj
