### ISSUE TITLE
Little typo

### ISSUE THREAD

**Issue by Emmo00** [sailscastshq/boring-stack#46]
hey @DominusKelvin , there is a little typo in the CONTRIBUTING.md. this could serve as a good first issue

![image](https://github.com/sailscastshq/boring-stack/assets/88244468/449821a1-5784-422f-b5a1-a48feaaf6ad2)

**Comment by Debjyoti0404** [comment]
I would like to work on this. Can anyone assign me?

**Comment by DominusKelvin** [comment]
Hey @Debjyoti0404 you can go ahead and work on it. Thank you so much
