### ISSUE TITLE
Add `Button` component to Mellow React template

### ISSUE THREAD

**Issue by babblebey** [sailscastshq/boring-stack#47]
Add `Button` Component for `mellow-react` template

Implementation

- Use `prop-types` for type checking - https://www.npmjs.com/package/prop-types
- Implement button `variant` via prop
- - primary
- - outline
- Implement button `width` via prop
- - fullwidth (boolean)
- Implement button `inactive` state via prop
- - inactive (boolean)
- Implement button link via `href` prop
- Implement events in via other `props`

![image](https://github.com/sailscastshq/boring-stack/assets/25631971/0d056aa3-3622-42bb-a4e6-2fab128135e1)

Parent Issue: #17

**Comment by babblebey** [comment]
.take

**Comment by DavidAjanaku** [comment]
is there any way to get the UI for this so I could work on the issue
