### ISSUE TITLE
Svelte page has a link for webpack that does not link to the homepage of the project

### ISSUE THREAD

**Issue by delight** [sailscastshq/boring-stack#61]
### Description
Svelte page has a link for webpack that does not link to the homepage of the project
...

### Current behavior
links to some akward page
...

### Expected behavior
 link to the homepage of the project
...

> Replace space in square bracket with `x` e.g `[x]`

[x] I have checked and this issue does not exist

**Comment by DominusKelvin** [comment]
Thanks @delight for taking the time to fix this.
