### ISSUE TITLE
Add basic docs

### ISSUE THREAD

**Issue by DominusKelvin** [sailscastshq/boring-stack#77]
## Introduction
- [x] Why the name
- [x] Who is it for
- [x] What's in the stack
- [x] Getting started

## The Basics
- [x] Routing
- [x] Navigation
- [x] Redirects
- [x] Shared data

## Guides
- [x] Authentication
- [x] Authorization
- [x] Database
- [x] Email
- [x] Session

## Deploy
- [x] Render

## Configurations
- [x] Type checking JS files

**Comment by lennyAiko** [comment]
With this it will become easier and faster to get started. Another thing we should also look at is the contents of each topic, since some info will be borrowed from other docs.

**Comment by DominusKelvin** [comment]
> With this it will become easier and faster to get started. Another thing we should also look at is the contents of each topic, since some info will be borrowed from other docs.

Yeah. I am linking out to other pages to avoid duplication of info. The goal is to present the quick getting started path in the docs and then for more in-depth folks can read in the respective docs.

![CleanShot 2024-01-31 at 19 55 24@2x](https://github.com/sailscastshq/boring-stack/assets/24433274/c3045e4f-8d38-419e-b917-5bd01b57ea6f)

**Comment by lennyAiko** [comment]
This linking is good enough.
