### ISSUE TITLE
Not showing errors diff and formatted error stacks in tests

### ISSUE THREAD

**Issue by MaNi4** [sailscastshq/boring-stack#97]
### Description
Hi, tests are still running/waiting without exiting and returning duration of tests and errors diff.

When I removed **presetSails()**, then errors messages from tests are showing, and tests successfully finished.
_bin/test.js_
`plugins: [**presetSails()**, assert(), runFailedTests(), apiClient('http://localhost:3333')]`

### Current behavior
Tests are still running/waiting without exiting and returning duration of tests and errors diff.

### Expected behavior
I want to achieve how it works in [Japa.dev documentation](https://japa.dev/docs/test-reporters#the-spec-reporter)

> Replace space in square bracket with `x` e.g `[x]`

[x] I have checked and this issue does not exist

**Comment by DominusKelvin** [comment]
Thanks for submitting this @MaNi4 I'll take a look shortly.

**Comment by DominusKelvin** [comment]
Hey @MaNi4 I am researching moving off Japa to the build in `node:test` and Playwright for testing in The Boring JavaScript Stack, I will close this issue because of that.
