### ISSUE TITLE
Issue with create-sails downloading tarball

### ISSUE THREAD

**Issue by ipseonet** [sailscastshq/boring-stack#98]
### Description

The create-sails npx command fails it's fetch command.

### Current behavior

Not fetching.
`○  Copying project files
└  Failed to download https://api.github.com/repos/sailscastshq/boring-stack/tarball/main: TypeError: fetch failed
`

### Expected behavior

fetch and create sails app

> Replace space in square bracket with `x` e.g `[x]`

[x ] I have checked and this issue does not exist

**Comment by DominusKelvin** [comment]
Hey @ipseonet I am thinking this might be a GitHub down time, can you try again and see if this issue persists?

**Comment by ipseonet** [comment]
> Hey @ipseonet I am thinking this might be a GitHub down time, can you try again and see if this issue persists?

It's been a while but the issue was resolved at some point, but I am now experiencing the same issue. When I use the address being fetched in the URL it downloads but not using the npx create-sails command.
